version: '3.5'

services:
  user-service:
    container_name: user-service
    image: shamim72/user-service:1.0.1
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    restart: always