version: '3.5'

services:
  user-service:
    container_name: user-service
    image: shamim72/user-service:1.0.1
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_URI=mysql
      - MYSQL_PORT=3307
      - MYSQ_USERNAME=root
      - MYSQ_PASS=root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:8.0.0
    restart: always
    environment:
      # MYSQL_DATABASE: db
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: user
      # Password for root access
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3307'
    expose:
      # Opens port 3307 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: